replicaCount: 3

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

persistence:
  enabled: true
  storageClass: "gp2"
  accessMode: ReadWriteOnce
  size: 1Gi

rabbitmq:
  username: "admin"
  password: "password"
  erlangCookie: "mysecretcookie"
